# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bids', '0002_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='descp',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='image1',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='image2',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='image3',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='image4',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
